version: '3.9'

services:
  app:
    build: .
    ports:
      - '3200:3200'
    environment:
      MONGO_URL: mongodb://mongo:27017/nic_auth
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
